[package]
name = "rasterization"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.41"
gl = "0.12"
nalgebra = "0.31"
glium = "0.31"
winit = "0.25"
k_board = "1.1.3"
